# Generated by Django 3.0.6 on 2020-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=500)),
                ('oc', models.CharField(default=None, max_length=50)),
                ('noc', models.CharField(default=None, max_length=50)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('attribute', models.CharField(default=None, max_length=200)),
                ('status', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
