# Generated by Django 3.0.6 on 2020-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagdata',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
