# Generated by Django 3.0.6 on 2020-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20200522_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagdata',
            name='attribute',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='noc',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='oc',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='subject',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tagdata',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
